###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "text": "Hello, World!"
}

###
POST http://localhost:8080/stream
Content-Type: application/json
Accept: text/event-stream

{
  "text": "who are you?"
}
